name: deploy
on:
  push:
    branches:
      - master
  watch:
    types: [started]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        if: github.actor == github.event.repository.owner.login
        uses: serverless/github-action@v1.53.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_LAMBDA_ROLE_ARN: ${{ secrets.AWS_LAMBDA_ROLE_ARN }}
          ACM_CERT_ARN: ${{ secrets.ACM_CERT_ARN }}
        with:
          args: "deploy --stage dev"
